spring.application.name=zerotrust-soc
# Cria um arquivo de banco de dados chamado "soc_db" na raiz do projeto
spring.datasource.url=jdbc:h2:file:./data/soc_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Nossa chave de Identidade Zero-Trust
soc.security.api-key=zt-token-secreto-2026